# Data Analytics Lab

## Practical 03: Summarize Mobile Usage Patterns Using Descriptive Statistics

### Objective
To analyze mobile usage data and summarize patterns using descriptive statistics such as:
- Mean
- Median
- Maximum
- Minimum
- Standard Deviation

In [1]:
import pandas as pd

In [2]:
data = {
    "User": ["A", "B", "C", "D", "E"],
    "Screen_Time_Hours": [5, 7, 4, 6, 8],
    "Data_Usage_GB": [2.5, 3.2, 1.8, 2.9, 3.5],
    "Calls_Minutes": [30, 45, 20, 35, 50],
    "App_Usage_Count": [20, 25, 15, 22, 28]
}

df = pd.DataFrame(data)

df

  User  Screen_Time_Hours  Data_Usage_GB  Calls_Minutes  App_Usage_Count
0    A                  5            2.5             30               20
1    B                  7            3.2             45               25
2    C                  4            1.8             20               15
3    D                  6            2.9             35               22
4    E                  8            3.5             50               28

In [3]:
df.describe()

       Screen_Time_Hours  Data_Usage_GB  Calls_Minutes  App_Usage_Count
count           5.000000        5.00000       5.000000         5.000000
mean            6.000000        2.78000      36.000000        22.000000
std             1.581139        0.66106      11.937336         4.949747
min             4.000000        1.80000      20.000000        15.000000
25%             5.000000        2.50000      30.000000        20.000000
50%             6.000000        2.90000      35.000000        22.000000
75%             7.000000        3.20000      45.000000        25.000000
max             8.000000        3.50000      50.000000        28.000000

In [4]:
mean_values = df.mean(numeric_only=True)

print("Mean Values:")
print(mean_values)

Mean Values:
Screen_Time_Hours     6.00
Data_Usage_GB         2.78
Calls_Minutes        36.00
App_Usage_Count      22.00
dtype: float64

In [5]:
median_values = df.median(numeric_only=True)

print("Median Values:")
print(median_values)

Median Values:
Screen_Time_Hours     6.0
Data_Usage_GB         2.9
Calls_Minutes        35.0
App_Usage_Count      22.0
dtype: float64

In [6]:
max_values = df.max(numeric_only=True)

print("Maximum Values:")
print(max_values)

Maximum Values:
Screen_Time_Hours     8.0
Data_Usage_GB         3.5
Calls_Minutes        50.0
App_Usage_Count      28.0
dtype: float64

In [7]:
min_values = df.min(numeric_only=True)

print("Minimum Values:")
print(min_values)

Minimum Values:
Screen_Time_Hours     4.0
Data_Usage_GB         1.8
Calls_Minutes        20.0
App_Usage_Count      15.0
dtype: float64

In [8]:
std_values = df.std(numeric_only=True)

print("Standard Deviation:")
print(std_values)

Standard Deviation:
Screen_Time_Hours     1.581139
Data_Usage_GB         0.661060
Calls_Minutes        11.937336
App_Usage_Count       4.949747
dtype: float64

## Result

Successfully summarized mobile usage patterns using descriptive statistics such as mean, median, minimum, maximum, and standard deviation.