# Data Analytics Lab
## Practical 01: Explore Student Grades Dataset

### Objective:
To calculate:
- Average Marks
- Highest Marks
- Lowest Marks
- Student-wise Total and Average

In [12]:
import pandas as pd
data = {
    "RollNo": [1, 2, 3, 4, 5],
    "Name": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Maths": [78, 92, 67, 88, 55],
    "Science": [85, 79, 72, 91, 60],
    "English": [88, 95, 70, 84, 58]
}

df = pd.DataFrame(data)

df

   RollNo   Name  Maths  Science  English
0       1   Amit     78       85       88
1       2   Neha     92       79       95
2       3  Rahul     67       72       70
3       4  Priya     88       91       84
4       5  Karan     55       60       58

In [13]:
average_marks = df[["Maths", "Science", "English"]].mean()
average_marks

Maths      76.0
Science    77.4
English    79.0
dtype: float64

In [14]:
highest_marks = df[["Maths", "Science", "English"]].max()
highest_marks

Maths      92
Science    91
English    95
dtype: int64

In [15]:
lowest_marks = df[["Maths", "Science", "English"]].min()
lowest_marks

Maths      55
Science    60
English    58
dtype: int64

In [16]:
df["Total"] = df[["Maths", "Science", "English"]].sum(axis=1)
df["Average"] = df["Total"] / 3

df[["RollNo", "Name", "Total", "Average"]]

   RollNo   Name  Total    Average
0       1   Amit    251  83.666667
1       2   Neha    266  88.666667
2       3  Rahul    209  69.666667
3       4  Priya    263  87.666667
4       5  Karan    173  57.666667

## Result:
Successfully calculated:
- Average Marks
- Highest Marks
- Lowest Marks
- Student-wise Total and Average